### ISSUE TITLE
-restrict flag is required for icpc by Docs

### ISSUE THREAD

**Issue by PolyachenkoYA** [PrincetonUniversity/install_lammps#2]
Hi,

I found that the [official docs](https://docs.lammps.org/Speed_intel.html) say "When using Intel compilers, `-restrict` is required and `-qopenmp` is highly recommended for CCFLAGS and LINKFLAGS". However, `lammps_mixed_prec_dellas.sh` does not have the `-restrict`. 

I checked and the compilation went successfully for me without `-restrict` so I am not sure what they meant, but still this discrepancy in recommendations exists so I am wondering if it was explored.

Additionally, they give "CCFLAG options for best performance are `-O2 -fno-alias -ansi-alias -qoverride-limits fp-model fast=2 -no-prec-div`" which are also not in our recommended script. I will be doing some simulations soon so I will have a chance to test this, but it will not be very systematic. Were these flags explored?

Thanks you

**Comment by jdh4** [comment]
Those directions appear to outdated since -restrict is not supported by the latest Intel OneAPI compilers. The option of -restrict is being added (as well as others) when using the older compilers. To see this add the following to the build script:

-D CMAKE_VERBOSE_MAKEFILE=ON \

If you find any options that give a speed-up then let us know.
